dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: EOmqDeaNXN5QSt3VyuUcR92zX0w3r+zT0aVaoEls81CIs1Mj0kryMGJ9UVgEvVn1kSjiHtiRf6tpv2HRjWbLYms/zwXD1wbGOiLHh8vMDWoDqByR7169PU0XDF+TG8KTduQgH9VGGDqE1ky3SlHIlaSqa1IEu7nO7/R28mfgsi6DYzA1/cN9+wm/P3pb2/qjYP0U1II+4XPjP7QoB6lDjX38K402qLmT0kAxDtMlisbUU9+9hisY7se+wYwkS+YqPY/zYMcO0PfVQEDH9rG7/JxwmLEyGm6UGrFhtI8EvRyFnhDd3XAAOc/OXbdj11hM7XylVr1Ui8R3lqgktH1KHK/P4yYPAQ1Lp5NBBTYMvZewCV4jVg8Mq1Lp/wwW9a1NbUOxNJGZa82H7zt8+tTbb0Cj2Mr6EPWdpWft709kEFNSrYQ0VsBN3xO3pOSGLRkwMD1Lui24p26ZAvRSo9zVgaWVKGnDRc9+1o3dQ37R75QbNvCYP4LkES0OE/B0n0mCsUEez41LF+BAw/HYKgm/UCgzv29yorVDwrpxPcY9Eeud0sAjf40wSUWv6G/lgwvP0oCd5YM8IauBG7xZ+mQlmSm1smD4p9BSEuSAqOpRMBg3JGZhniVyryRhJ6ktujk/HQ2q48HjcGzNwbZ1NWXvlqzwk9zqx1FDUffVouZHvOU=
