global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_lugovov'
