version: '3.3'
services:
  post_db:
    image: mongo:${DB_VER}
    container_name: best_db_ever
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    container_name: best_ui_ever
    ports:
      - ${SRC_PORT}:${DST_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    container_name: best_post_ever
    image: ${USERNAME}/post:${POST_VER}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    container_name: best_comment_ever
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
