kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: YuwYvtv5i5c9So9ppNkkmYH2LqSwlEIl2Re8t+nu/UI=
      - identity: {}
